### PR TITLE
Product render fix #24

### LINKED ISSUE #24: Products Aren't Rendering
I'm going to see what's wrong

### PR DESCRIPTION
**Pull request by andferguson**
I fixed the Home component so it renders!

### CODE REVIEW

File: client/components/Home.js [hunk 1]
```diff
@@ -1,44 +1,46 @@
...
     super(props)
     this.state = {
-      selected: 'all',
-      filteredProd: this.props.products
+      filter: 'all'
     }
   }
 
-  filterProducts = (category) => {
+  handelFilter = event => {
```
Comment (maddieeiddam) [inline client/components/Home.js]: should this be handleFilter?

File: client/components/Home.js [hunk 2]
```diff
@@ -1,44 +1,46 @@
...
   render() {
+    if (!this.props.products.length || !this.props.categories.length) {
+      return <span />
+    }
     return (
       <div>
         <SideBar
-          filterProducts={this.filterProducts}
-          categories={this.state.categories}
+          handelFilter={this.handelFilter}
```
Comment (maddieeiddam) [inline client/components/Home.js]: oh - it's spelled the same down here.  i guess it's fine.
